[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
libs = ["contracts/lib"]
broadcast = "contracts/broadcast"

fs_permissions = [{ access = "read-write", path = "./"}]
show_progress=true
gas_reports = ["*"]
cbor_metadata = true

remappings = [
    "forge-std/=contracts/lib/forge-std/src/",
    "@eigenlayer-middleware/=contracts/lib/eigenlayer-middleware/",
    "@eigenlayer-contracts/=contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
    "@openzeppelin/=contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/"
]

solc_version = '0.8.27'

# If set to true, changes compilation pipeline to go through the new IR optimizer.
via_ir = false
# Whether or not to enable the Solidity optimizer.
optimizer = true
# The number of runs specifies roughly how often each opcode of the deployed code will be executed
# across the life-time of the contract. This means it is a trade-off parameter between code size (deploy cost)
# and code execution cost (cost after deployment).
optimizer_runs = 200

# An array of file paths from which warnings should be ignored during compilation.
ignored_warnings_from = [
    "test",
    "lib"
]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
holesky = "${RPC_HOLESKY}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
